-- MySQL Script generated by MySQL Workbench
-- 09/08/16 21:44:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema admin_warrior
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema admin_warrior
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `admin_warrior` DEFAULT CHARACTER SET utf8 ;
USE `admin_warrior` ;

-- -----------------------------------------------------
-- Table `admin_warrior`.`adres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`adres` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`adres` (
  `adres_id` INT NOT NULL AUTO_INCREMENT,
  `adres_ulica` VARCHAR(45) NULL,
  `adres_miejscowosc` VARCHAR(45) NOT NULL,
  `adres_kod_pocztowy` VARCHAR(45) NOT NULL,
  `adres_poczta` VARCHAR(45) NOT NULL,
  `adres_telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`adres_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`konto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`konto` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`konto` (
  `konto_id` INT NOT NULL AUTO_INCREMENT,
  `konto_login` VARCHAR(45) NOT NULL,
  `konto_haslo` VARCHAR(45) NOT NULL,
  `konto_uprawnienia` VARCHAR(45) NULL,
  PRIMARY KEY (`konto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`pracownik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`pracownik` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`pracownik` (
  `pracownik_id` INT NOT NULL AUTO_INCREMENT,
  `pracownik_imie` VARCHAR(45) NOT NULL,
  `pracownik_nazwisko` VARCHAR(45) NOT NULL,
  `pracownik_wynagrodzenie` INT NULL,
  `pracownik_adres_id_fk` INT NOT NULL,
  `pracownik_typ` VARCHAR(45) NOT NULL,
  `pracownik_data_zatrudnienia` DATETIME NOT NULL,
  `pracownik_data_zwolnienia` DATETIME NULL,
  `pracownik_konto_id_fk` INT NOT NULL,
  PRIMARY KEY (`pracownik_id`),
  INDEX `fk_pracownik_adres_id_idx` (`pracownik_adres_id_fk` ASC),
  INDEX `fk_pracownik_konto_id_idx` (`pracownik_konto_id_fk` ASC),
  CONSTRAINT `fk_pracownik_adres_id`
    FOREIGN KEY (`pracownik_adres_id_fk`)
    REFERENCES `admin_warrior`.`adres` (`adres_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pracownik_konto_id`
    FOREIGN KEY (`pracownik_konto_id_fk`)
    REFERENCES `admin_warrior`.`konto` (`konto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`dane_klienta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`dane_klienta` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`dane_klienta` (
  `dane_klienta_id` INT NOT NULL AUTO_INCREMENT,
  `dane_klienta_wzrost` INT NULL,
  `dane_klienta_waga` INT NULL,
  `dane_klienta_plec` VARCHAR(45) NULL,
  `dane_klienta_data_ur` VARCHAR(45) NULL,
  `dane_klienta_stan` VARCHAR(45) NULL,
  PRIMARY KEY (`dane_klienta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`zainteresowania_opis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`zainteresowania_opis` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`zainteresowania_opis` (
  `zainteresowania_opis_id` INT NOT NULL AUTO_INCREMENT,
  `zainteresowania_opis_opis` VARCHAR(1000) NULL,
  PRIMARY KEY (`zainteresowania_opis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`zainteresowania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`zainteresowania` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`zainteresowania` (
  `zainteresowania_id` INT NOT NULL AUTO_INCREMENT,
  `zainteresowania_nazwa` VARCHAR(100) NULL,
  `zainteresowania_zainteresowania_opis_id_fk` INT NULL,
  PRIMARY KEY (`zainteresowania_id`),
  CONSTRAINT `fk_zainteresowania_zainteresowania_opis_id`
    FOREIGN KEY (`zainteresowania_id`)
    REFERENCES `admin_warrior`.`zainteresowania_opis` (`zainteresowania_opis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`klient` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`klient` (
  `klient_id` INT NOT NULL AUTO_INCREMENT,
  `klient_imie` VARCHAR(45) NOT NULL,
  `klient_nazwisko` VARCHAR(45) NOT NULL,
  `klient_adres_id_fk` INT NOT NULL,
  `klient_konto_id_fk` INT NOT NULL,
  `klient_dane_klienta_id_fk` INT NULL,
  `klient_zainteresowania_id_fk` INT NULL,
  PRIMARY KEY (`klient_id`),
  INDEX `fk_klient_adres_id_idx` (`klient_adres_id_fk` ASC),
  INDEX `fk_klient_konto_id_idx` (`klient_konto_id_fk` ASC),
  INDEX `fk_klient_dane_klienta_id_idx` (`klient_dane_klienta_id_fk` ASC),
  INDEX `fk_klient_zainteresowania_id_idx` (`klient_zainteresowania_id_fk` ASC),
  CONSTRAINT `fk_klient_adres_id`
    FOREIGN KEY (`klient_adres_id_fk`)
    REFERENCES `admin_warrior`.`adres` (`adres_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klient_konto_id`
    FOREIGN KEY (`klient_konto_id_fk`)
    REFERENCES `admin_warrior`.`konto` (`konto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klient_dane_klienta_id`
    FOREIGN KEY (`klient_dane_klienta_id_fk`)
    REFERENCES `admin_warrior`.`dane_klienta` (`dane_klienta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klient_zainteresowania_id`
    FOREIGN KEY (`klient_zainteresowania_id_fk`)
    REFERENCES `admin_warrior`.`zainteresowania` (`zainteresowania_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`znajomi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`znajomi` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`znajomi` (
  `znajomi_id` INT NOT NULL AUTO_INCREMENT,
  `znajomi_klient_id_fk` INT NOT NULL,
  `znajomi_klient2_id_fk` INT NOT NULL,
  PRIMARY KEY (`znajomi_id`),
  INDEX `fk_ulubione_klient_id_idx` (`znajomi_klient_id_fk` ASC),
  INDEX `fk_ulubione_klient2_id_idx` (`znajomi_klient2_id_fk` ASC),
  CONSTRAINT `fk_znajomi_klient_id`
    FOREIGN KEY (`znajomi_klient_id_fk`)
    REFERENCES `admin_warrior`.`klient` (`klient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_znajomi_klient2_id`
    FOREIGN KEY (`znajomi_klient2_id_fk`)
    REFERENCES `admin_warrior`.`klient` (`klient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`zdjecie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`zdjecie` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`zdjecie` (
  `zdjecie_id` INT NOT NULL AUTO_INCREMENT,
  `zdjecie_sciezka` VARCHAR(200) NOT NULL,
  `zdjecie_tag` VARCHAR(200) NULL,
  `zdjecie_ocena_suma` INT NULL,
  `zdjecie_ocena_ilosc` INT NULL,
  `zdjecie_profilowe` VARCHAR(45) NULL,
  PRIMARY KEY (`zdjecie_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin_warrior`.`klient_zdjecie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin_warrior`.`klient_zdjecie` ;

CREATE TABLE IF NOT EXISTS `admin_warrior`.`klient_zdjecie` (
  `klient_zdjecie_id` INT NOT NULL AUTO_INCREMENT,
  `klient_zdjecie_klient_id_fk` INT NOT NULL,
  `klient_zdjecie_zdjecie_id_fk` INT NOT NULL,
  PRIMARY KEY (`klient_zdjecie_id`),
  INDEX `fk_klient_zdjecie_klient_id_idx` (`klient_zdjecie_klient_id_fk` ASC),
  INDEX `fk_klient_zdjecie_zdjecie_id_idx` (`klient_zdjecie_zdjecie_id_fk` ASC),
  CONSTRAINT `fk_klient_zdjecie_klient_id`
    FOREIGN KEY (`klient_zdjecie_klient_id_fk`)
    REFERENCES `admin_warrior`.`klient` (`klient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_klient_zdjecie_zdjecie_id`
    FOREIGN KEY (`klient_zdjecie_zdjecie_id_fk`)
    REFERENCES `admin_warrior`.`zdjecie` (`zdjecie_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
